# Generated by Django 4.2.7 on 2023-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('pub_year', models.DateTimeField(auto_now_add=True, verbose_name='publication year')),
                ('isbn', models.CharField(max_length=13, verbose_name='isbn')),
            ],
            options={
                'verbose_name': ('Book',),
                'verbose_name_plural': 'Books',
                'ordering': ['pub_year'],
            },
        ),
    ]
